---CREATE DATABASE TPCDS AUTOMATIC STORAGE NO ON /TPCDS/tpcds_flat/db2fs PAGESIZE 16384 AUTOCONFIGURE APPLY NONE;
create database tpcds AUTOMATIC STORAGE YES  PAGESIZE 16384 AUTOCONFIGURE APPLY NONE;
UPDATE DB CFG FOR TPCDS USING LOGPRIMARY 100;
UPDATE DB CFG FOR TPCDS USING SORTHEAP 1000 BUFFPAGE 20000;
---the following line enables cgs discovery through auto-runstats
UPDATE DB CFG FOR TPCDS USING AUTO_CG_STATS ON;
CONNECT TO TPCDS;
CONNECT RESET;

