connect to tpcds;

CREATE TEMPORARY TABLESPACE temp16k PAGESIZE 16K
BUFFERPOOL BP_16K;

--CREATE USER TEMPORARY TABLESPACE usertemp16k IN DATABASE PARTITION GROUP pdpg PAGESIZE 16K
--BUFFERPOOL BP_16K;

--CREATE TABLESPACE ts_pd_data_001 IN DATABASE PARTITION GROUP pdpg PAGESIZE 16K 
--BUFFERPOOL BP_16K;

--CREATE TABLESPACE ts_pd_indx_001 IN DATABASE PARTITION GROUP pdpg PAGESIZE 16K 
--BUFFERPOOL BP_16K;

--CREATE TABLESPACE ts_sd_small_001 IN DATABASE PARTITION GROUP sdpg PAGESIZE 16K 
--BUFFERPOOL BP_16K;

CREATE USER TEMPORARY TABLESPACE usertemp16k PAGESIZE 16K
BUFFERPOOL BP_16K;

CREATE TABLESPACE ts_pd_data_001 PAGESIZE 16K 
BUFFERPOOL BP_16K;

CREATE TABLESPACE ts_pd_indx_001 PAGESIZE 16K 
BUFFERPOOL BP_16K;

CREATE TABLESPACE ts_sd_small_001 PAGESIZE 16K 
BUFFERPOOL BP_16K;

commit work;

connect to tpcds;
drop tablespace tempspace1;

commit work;

connect reset;
