connect to tpcds;

set current schema TPCDS;

ALTER TABLE TPCDS.CUSTOMER ADD COLUMN C_CUSTOMER_SK2 INT;
UPDATE TPCDS.CUSTOMER SET C_CUSTOMER_SK2 = C_CUSTOMER_SK + MOD(C_CUSTOMER_SK,3);

ALTER TABLE TPCDS.CUSTOMER_ADDRESS ADD COLUMN CA_ADDRESS_SK2 INT;
UPDATE TPCDS.CUSTOMER_ADDRESS SET CA_ADDRESS_SK2 = CA_ADDRESS_SK + MOD(CA_ADDRESS_SK,3);

ALTER TABLE TPCDS.CUSTOMER_DEMOGRAPHICS ADD COLUMN CD_DEMO_SK2 INT;
UPDATE TPCDS.CUSTOMER_DEMOGRAPHICS SET CD_DEMO_SK2 = CD_DEMO_SK + MOD(CD_DEMO_SK,3);

ALTER TABLE TPCDS.HOUSEHOLD_DEMOGRAPHICS ADD COLUMN HD_DEMO_SK2 INT;
UPDATE TPCDS.HOUSEHOLD_DEMOGRAPHICS SET HD_DEMO_SK2 = HD_DEMO_SK + MOD(HD_DEMO_SK,3);

commit;

connect reset;